### ISSUE TITLE
Feature - Model Index

### ISSUE THREAD

**Issue by bhaskell7901** [bhaskell7901/taskit#10]
Implement an index model with the following configurations:

* User has many JobOffer
* JobOffer has one user
* User has many Job
* Job has one user (FK service_provider_id & customer_id)
* User has one ServiceRange
* ServiceRange has one User
* Profile has one User
* User has many Profile
* Location has one Profile
* Profile has one Location
* Location has one Profile
* JobOffer has one Service
* Service has many JobOffer
* Job has one Service
* Service has many Job
* Job has one status
* Status has many Job
* Status has one StatusName
* StatusName has one Status
* Job has one Location
* Location has many Job

**Comment by EdwinHdz04** [comment]
completed
